name: Test

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["pypy-3.7", "pypy-3.8", "pypy-3.9", "3.7", "3.8", "3.9", "3.10", "3.11"]
        pytest-tox-version: ["pytest5", "pytest6", "pytest7"]
        include:
          # Add new variables to existing jobs
          - {python-version: "pypy-3.7", python-tox-version: "pypy37"}
          - {python-version: "pypy-3.8", python-tox-version: "pypy38"}
          - {python-version: "pypy-3.9", python-tox-version: "pypy39"}
          - {python-version: "3.7", python-tox-version: "py37"}
          - {python-version: "3.8", python-tox-version: "py38"}
          - {python-version: "3.9", python-tox-version: "py39"}
          - {python-version: "3.10", python-tox-version: "py310"}
          - {python-version: "3.11", python-tox-version: "py311"}
        exclude:
          # Remove jobs with incompatible combinations
          - {python-version: "3.10", pytest-tox-version: "pytest5"}
          - {python-version: "3.11", pytest-tox-version: "pytest5"}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key:
            ${{ matrix.os }}-${{ matrix.python-version }}-v1-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/tox.ini') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python-version }}-v1-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
          python -m pip install -U tox

      - name: Tox tests
        run: |
          tox -e ${{ matrix.python-tox-version }}-${{ matrix.pytest-tox-version }}
